#
#seata:
#  application-id: ${spring.application.name}
#  tx-service-group: default_tx_group
#
#  # Seata 的注册方式为 nacos
#  registry:
#    type: nacos
#    nacos:
#      namespace: zcctframe
#      group: seata-group
#      server-addr: 127.0.0.1:8848
#      username: zcct
#      password: zcct
#  # Seata 的配置中心为 nacos
#  config:
#    type: nacos
#    nacos:
#      namespace: zcctframe
#      group: seata-group
#      server-addr: 127.0.0.1:8848
#      username: zcct
#      password: zcct
#
#
#spring:
#  datasource:
#
#    type: com.alibaba.druid.pool.DruidDataSource #引入druid数据源
#    #数据源基本信息，也可放在druid下
#    url: jdbc:mysql://127.0.0.1:3306/zcct-base?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: zclvct
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      # 初始连接数
#      initial-size: 50
#      # 最小连接数
#      min-idle: 50
#      # 最大连接数
#      max-active: 1000
#      # 获取连接超时时间
#      max-wait: 30000
#      # 连接有效性检测时间
#      time-between-eviction-runs-millis: 60000
#      # 连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      # 连接在池中最大生存的时间
#      max-evictable-idle-time-millis: 900000
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 检测连接是否有效
#      validation-query: select 1
#      # 配置监控统计
#      webStatFilter:
#        enabled: true
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: admin
#        login-password: admin
#      filter:
#        stat:
#          enabled: true
#          # 记录慢SQL
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
#rocketmq:
#  name-server: 127.0.0.0:9876 # 访问地址
#  producer:
#    group: Zcct_Group # 必须指定group
#    send-message-timeout: 3000 # 消息发送超时时长，默认3s
#    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
#    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
