#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource #引入druid数据源
#    #数据源基本信息，也可放在druid下
#    url: jdbc:mysql://127.0.0.1:3306/zcct-user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: zclvct
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      #druid数据源专有配置
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 600000
#      # 主要配置以上几个即可
#      timeBetweenEvictionRunsMillis: 600000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#
#      #配置监控统计拦截的filters：stat:监控统计、self4j(使用log4j的记得导入log4j的依赖）：日志记录、wall：防御sql注入 此处配置不能遗漏服务sql监控台不能监控sql
#      filter:
#        slf4j:
#          enabled: true
#        stat:
#          enabled: true
#          merge-sql: true
#          slow-sql-millis: 5000
#        wall:
#          enabled: true
#      #配置stat-view-servlet
#      stat-view-servlet:
#        enabled: true
#        login-username: admin
#        login-password: 123456
#        reset-enable: false
#      #配置web-stat-filter
#      web-stat-filter:
#        enabled: true
